kind: Deployment
apiVersion: apps/v1
metadata:
  name: rs-app
  namespace: default
  labels:
    app: rs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rs-app
  template:
    metadata:
      labels:
        app: rs-app
    spec:
      volumes:
        - name: rs-conf
          hostPath:
            path: /opt/riskscanner/conf
            type: ''
        - name: rs-logs
          hostPath:
            path: /opt/riskscanner/logs
            type: ''
      containers:
        - name: rs-app
          image: 'saintenvoy/riskscanner:v1.6.1'
          ports:
            - name: http-8088
              containerPort: 8088
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: rs-conf
              mountPath: /opt/riskscanner/conf
            - name: rs-logs
              mountPath: /opt/riskscanner/logs
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
